version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: whatsapp_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # WPPConnect Server instances will be created dynamically
  # This is just a template for reference
  wppconnect-template:
    image: wppconnect/server:latest
    profiles:
      - template
    environment:
      - PORT=21465
      - HOST=0.0.0.0
      - LOG_LEVEL=silly
      - LOG_LOGGER=false
      - LOG_LOGGER_LEVEL=silly
    volumes:
      - wppconnect_tokens:/app/tokens
      - wppconnect_downloads:/app/downloads
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  wppconnect_tokens:
  wppconnect_downloads:

networks:
  default:
    name: whatsapp-saas-network
